# Generated by Django 4.0.5 on 2022-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('BoardID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='BID')),
                ('subject', models.CharField(max_length=60, unique=True)),
                ('context', models.CharField(max_length=100)),
                ('isActivate', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CID')),
                ('contents', models.TextField(max_length=200)),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField(max_length=2000)),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
